//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_CustomSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean RTrigger
        {
            get
            {
                return SteamVR_Actions.customSet_RTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.customSet_Menu;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.customSet_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean LTrigger
        {
            get
            {
                return SteamVR_Actions.customSet_LTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LGrip
        {
            get
            {
                return SteamVR_Actions.customSet_LGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean RGrip
        {
            get
            {
                return SteamVR_Actions.customSet_RGrip;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.customSet_Haptic;
            }
        }
    }
}
